name: Create Snowflake Roles and Users

on:
  push:
    branches:
      - main

jobs:
  create_roles_and_users:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    #- name: Install SnowSQL CLI
     # run: |
      #  curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.18-linux_x86_64.bash
       # bash snowsql-1.2.18-linux_x86_64.bash

    - name: Create role and user
      env:
        SNOWSQL_ACCOUNT: <Snowflake account name>
        SNOWSQL_USER: <Snowflake user name>
        SNOWSQL_PASSWORD: ${{ secrets.SNOWSQL_PASSWORD }}
        SNOWSQL_ROLE: <Snowflake role name>
     # run: |
       # snowsql -a $SNOWSQL_ACCOUNT -u $SNOWSQL_USER -p $SNOWSQL_PASSWORD -r $SNOWSQL_ROLE -q "CREATE ROLE my_role;"
        #snowsql -a $SNOWSQL_ACCOUNT -u $SNOWSQL_USER -p $SNOWSQL_PASSWORD -r $SNOWSQL_ROLE -q "CREATE USER my_user PASSWORD 'my_password';"
      #  echo 'CREATE SESSION POLICY my_session_policy FROM JSON '\''file://session_policy.json'\'';' | snowsql -a $SNOWSQL_ACCOUNT -u $SNOWSQL_USER -p $SNOWSQL_PASSWORD  
  
